#!/bin/bash
RVERS=R-4.1.1
# Download the current version of R
wget https://cran.r-project.org/src/base/R-4/$RVERS.tar.gz

# Extract the tar.gz file
tar -xzf $RVERS.tar.gz

# Load the modules that we'll need to compile R
module load python/3.7.0
module load gcc/8.3.0

# Change to the directory with the source code
cd $RVERS 

# Execute the configure script
./configure --with-pcre1

# Assuming that everything went OK, let's try to compile this thing. 
make -j 8 

